/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trafficmonit;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        new TrafficResolver().resolve();
    }
}
